import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const sourceDir = path.join(root, "src");
const outputDir = path.join(root, "dist");

const stripImports = source => source.replace(/^import .*?;\r?\n/gm, "");
const stripExports = source => source.replace(/^export\s+/gm, "");

const [dataSource, onePieceSource, engineSource, appSource] = await Promise.all([
  readFile(path.join(sourceDir, "data.js"), "utf8"),
  readFile(path.join(sourceDir, "packs", "one-piece.js"), "utf8"),
  readFile(path.join(sourceDir, "engine.js"), "utf8"),
  readFile(path.join(sourceDir, "app.js"), "utf8")
]);

const bundle = `/* Generated by build.mjs. Edit files in src/, then run npm run build. */
(() => {
"use strict";

${stripExports(stripImports(dataSource))}

${stripExports(stripImports(onePieceSource))}

// engine.js imports this export under an alias; keep the same name in the concatenated bundle.
const onePieceSignatureCost = signatureCost;

${stripExports(stripImports(engineSource))}

${stripExports(stripImports(appSource))}
})();
`;

await mkdir(outputDir, { recursive: true });
await writeFile(path.join(outputDir, "app.bundle.js"), bundle, "utf8");
console.log("已生成 dist/app.bundle.js");
